sudo: required
services:
  - docker

before_install:
  - docker build -t sudharsan/casts-docker-react -f Dockerfile.dev .

script:
  - docker run sudharsan/casts-docker-react npm run test -- --coverage